### ISSUE TITLE
Example code not `SyntaxError: Unexpected token =`

### ISSUE THREAD

**Issue by mattcanty** [vandium-io/lambda-tester#20]
I'm having problems using `lambda-tester`. I have a fresh project and the following files:

**index.js**
```
exports.handler = function( event, context, callback ) {
  callback( null, 'success!' );
}
```

**test/index.test.js**
```
const LambdaTester = require( 'lambda-tester' );

const myHandler = require( '../index' ).handler;

describe( 'handler', function() {

    it( 'test success', function() {

        return LambdaTester( myHandler )
            .event( { name: 'Fred' } )
            .expectResult();
    });
});
```

Yet I get the following error:
```
matthewcanty:~/workspace (master) $ mocha test
/home/ubuntu/workspace/node_modules/lambda-tester/lib/runner.js:95
    constructor( method, verifier, options = {} ) {
                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/lambda-tester/lib/index.js:3:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/test/readMusicdown.test.js:1:84)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /mnt/shared/lib/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/mnt/shared/lib/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/mnt/shared/lib/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/mnt/shared/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

**Comment by richardhyatt** [comment]
Which version of Node are you using? Make sure you are using version 6.10 or higher

**Comment by mattcanty** [comment]
My bad. Me read readme next time.

Thanks
