### ISSUE TITLE
Error: callback called

### ISSUE THREAD

**Issue by tobsn** [vandium-io/lambda-tester#5]
I keep getting:
```
  1) handler failed invocation: p= 1231231234:
     Error: callback called
      at node_modules/lambda-tester/lib/index.js:81:29
      at index.js:8:4
      at node_modules/q/q.js:1924:17
      at flush (node_modules/q/q.js:108:17)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**lambda function (example):**
```
'use strict';

exports.handler = ( event, context, callback ) => {
	if( !event.p || !/^[0-9-+()\s]+$/.test( event.p ) ) {
		callback( null, { valid: false });
	}
	else {
		callback( null, {
			valid: ( error ) ? false: true,
			data: ( error ) ? false : { p: event.p }
		});
	}
};
```

**test:**
```
const expect = require( 'chai' ).expect;
const LT = require( 'lambda-tester' );
const MF = require( './index' ).handler;

describe( 'handler', () => {
	[
		'1231231234'
	].forEach( ( number ) => {
		it( 'successful invocation: p=' + number, ( done ) => {
			LT( MF )
				.event({ p: number })
				.expectSucceed( ( result ) => {
					console.log(result);
					expect( result.valid ).to.be.true;
				})
				.verify( done );
		});
	});
});
```

**Comment by richardhyatt** [comment]
try:

```js
const expect = require( 'chai' ).expect;
const LT = require( 'lambda-tester' );
const MF = require( './index' ).handler;

describe( 'handler', () => {
    [
        '1231231234'
    ].forEach( ( number ) => {
        it( 'successful invocation: p=' + number, ( done ) => {
            return LT( MF )
                .event({ p: number })
                .expectResult( ( result ) => {
                    console.log(result);
                    expect( result.valid ).to.be.true;
                });
        });
    });
});
```

**Comment by tobsn** [comment]
`TypeError: LT(...).event(...).expectResult(...).verify is not a function`

**Comment by richardhyatt** [comment]
you don't need the verify - follow my code - don't forget the "return LT( MF )"

**Comment by richardhyatt** [comment]
use `expectResult()` to verify that `callback( null, result )` was called. Call `expectSucceed()` only if you call `context.succeed()`. For more info see the [docs](https://github.com/vandium-io/lambda-tester/blob/master/docs/main.md#verifying-callbacks).
